### ISSUE TITLE
Changing the API a bit to reflect a different domain name

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#33]
@AddisonFreeman could you please get me on skype when you have a minute to chat.

**Comment by robgpeak** [comment]
@AddisonFreeman could you please do me a favor and change the URL of your API to rewardeverywhere.co   Then let me know so I can upload it and test it to make sure it's working as expected.  I think that's all that needs to be done.

**Comment by AddisonFreeman** [comment]
Will get to this first thing in the AM. Should take under an hour, am I okay to invoice you for it?

Addison Freeman

**Comment by cgladue** [comment]
@AddisonFreeman @robgpeak its **api.rewardseverywhere.co**

**Comment by robgpeak** [comment]
Of course on the invoice Addison.

**Comment by robgpeak** [comment]
I am still having issues with 1.7.9

1. Install the extension as an unauthenticated user, then from the browser extension itself, attempt to login, but purposefully enter the wrong password and when you click save, nothing happens.  It does not come back and tall you the password is incorrect.

2. The popup does not show up when I go to a merchant like https://www.godaddy.com/ or https://www.jcpenney.com where it used to.

3. The logos to not pop in above the google search results like they used to.

<img width="1016" alt="Screen Shot 2019-09-26 at 10 50 29 AM" src="https://user-images.githubusercontent.com/28393235/65699632-5df53c80-e04c-11e9-9f00-9cd5feb69dc7.png">

**Comment by AddisonFreeman** [comment]
<img width="925" alt="Screen Shot 2019-09-26 at 10 17 32 AM" src="https://user-images.githubusercontent.com/5950267/65701473-f7b9eb00-e046-11e9-92d9-e3a91d626da3.png">
@robgpeak 
So @cgladue, I'm still getting bad endpoint responses. Can you confirm that they should all work the same as they did when they were complinks.co URLs

**Comment by AddisonFreeman** [comment]
@robgpeak go ahead and try out version 1.7.10 I just pushed. It will solve issues 2 and 3. The login error message is in Chad's hands with a broken /authenticate endpoint.

**Comment by cgladue** [comment]
@AddisonFreeman hey addison, not sure why its failing on your end, but nothing changed with the API and when i submit the request using SoapUI it returns exactly as expected
![image](https://user-images.githubusercontent.com/7914133/65731907-940ade80-e095-11e9-8ea7-8172693cd2d1.png)

**Comment by robgpeak** [comment]
OK, 2 and 3 are working as expected, but 1 is still an issue.  Please let me know when we can get it solved so I can send a notification to our users.

**Comment by robgpeak** [comment]
Shit, actually now that I am playing with it, I noticed after I DO get to a site (advertiser's website) after the redirection, the notification pop up window telling me that my points for this trip have been activated doe NOT show up.  Test it yourself.

**Comment by robgpeak** [comment]
https://www.loom.com/share/72f3712b4f524b24b859ebe7ee58ae6b

**Comment by AddisonFreeman** [comment]
Can we do a call first thing in the AM? I’ll look at this tonight. How is 10am EST?

Addison Freeman

**Comment by robgpeak** [comment]
Sure, even earlier is ok. Send me a message on Skype in the morning.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Ready?
